services:
  mysql_test_laravel_api:
    image: mysql:8.0
    container_name: test_laravel_api_db
    # restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    ports:
      - "3301:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - test_laravel_api

  phpmyadmin_test_laravel_api:
    image: phpmyadmin/phpmyadmin
    container_name: test_laravel_api_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql_test_laravel_api
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8082:80"
    networks:
      - test_laravel_api

  app_test_laravel_api:
    build:
      context: . # Points to the directory with your Dockerfile
      dockerfile: Dockerfile
    container_name: test_laravel_api_apache
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
      - "6002:6001" # Expose WebSocket port
    volumes:
      - .:/var/www/html
    networks:
      - test_laravel_api
    environment:
      DB_HOST: mysql_test_laravel_api
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: user
      DB_PASSWORD: secret
    depends_on:
      - mysql_test_laravel_api
    command: /bin/sh -c "chmod -R 777 /var/www/html/storage && php artisan websockets:serve & php-fpm"

  webserver_test_laravel_api:
    image: nginx:alpine
    container_name: test_laravel_api_nginx
    restart: unless-stopped
    ports:
      - "9001:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - test_laravel_api

networks:
  test_laravel_api:


volumes:
  dbdata:
